version: '2'
services:
  mysql:
    build: ./mysql
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
  php:
    build: ./php
    ports:
      - '81:80'
    volumes:
      - ./../php:/var/www/html
    depends_on:
      - mysql
    extra_hosts:
      - "elering.sise:10.1.2.50"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
       - mysql:mysql
    ports:
       - 82:80
    environment:
       PMA_HOST: mysql
       PMA_USER: root
       PMA_PASSWORD: root
  redis:
    image: redis
    ports:
      - 6379:6379     